# Inserts a blank line between shell prompts
add_newline = true

# Prompt format
format = """
[](fg:#ff5555)\
$username\
[](fg:#ff5555 bg:#bd93f9)\
$directory\
[](fg:#bd93f9 bg:#8be9fd)\
$git_branch\
$git_status\
[](fg:#8be9fd bg:#50fa7b)\
$nodejs\
[](fg:#50fa7b bg:#f1fa8c)\
$time\
[](fg:#f1fa8c)\
$character
"""

# Username module
[username]
style_user = "bg:#ff5555 fg:#282a36"
format = "[$user]($style)"
show_always = true

# Directory module
[directory]
style = "bg:#bd93f9 fg:#282a36"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Git branch module
[git_branch]
style = "bg:#8be9fd fg:#282a36"
format = "[ $branch]($style)"

# Git status module
[git_status]
style = "bg:#8be9fd fg:#282a36"
format = "[$all_status]($style)"

# Node.js module
[nodejs]
style = "bg:#50fa7b fg:#282a36"
format = "[ $version]($style)"

# Time module
[time]
disabled = false
time_format = "%R"
style = "bg:#f1fa8c fg:#282a36"
format = "[ $time]($style)"

# Character module
[character]
success_symbol = "[➜](bold fg:#50fa7b)"
error_symbol = "[✗](bold fg:#ff5555)"

