# Adds a blank line between prompts for visual breathing room
add_newline = true

# Main prompt format
format = """

[](fg:#3d59a1)\
$directory\
[](fg:#3d59a1 bg:#2b3462)\
$git_branch\
[](fg:#2b3462 bg:#394b70)\
$git_status\
[](fg:#394b70 bg:#565f89)\
$nodejs\
[](fg:#565f89 bg:#7aa2f7)\
$python\
[](fg:#7aa2f7 bg:#414868)\
$memory_usage\
[](fg:#414868 bg:#e0af68)\
$battery\
[](fg:#e0af68 bg:#bb9af7)\
$time\
[](fg:#bb9af7)\
$character
"""

# Directory module
[directory]
style = "bg:#3d59a1 fg:#c0caf5"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ""

# Git branch
[git_branch]
style = "bg:#2b3462 fg:#c0caf5"
format = "[ $symbol$branch ]($style)"
symbol = ""

# Git status
[git_status]
style = "bg:#394b70 fg:#c0caf5"
format = "[ $all_status ]($style)"

# Node.js
[nodejs]
style = "bg:#565f89 fg:#c0caf5"
format = "[ $version ]($style)"

# Python
[python]
style = "bg:#7aa2f7 fg:#1a1b26"
format = "[🐍 $version ($virtualenv) ]($style)"
python_binary = "python3"

# Memory Usage
[memory_usage]
disabled = false
threshold = 50
style = "bg:#414868 fg:#c0caf5"
format = "[ RAM: $ram_pct ]($style)"

# Battery
[battery]
format = "[ $symbol$percentage ]($style)"

[[battery.display]]
threshold = 90
style = "bg:#e0af68 fg:#1a1b26"

# Time
[time]
disabled = false
time_format = "%R"
style = "bg:#bb9af7 fg:#1a1b26"
format = "[ $time ]($style)"

# Prompt symbol
[character]
success_symbol = "[➜](bold fg:#9ece6a)"
error_symbol = "[✗](bold fg:#f7768e)"

