# Inserts a blank line between shell prompts
add_newline = true

# Prompt format
format = """
[](fg:#ff5555)\
$directory\
[](fg:#ff5555 bg:#bd93f9)\
[](fg:#bd93f9 bg:#8be9fd)\
$git_branch\
[](fg:#8be9fd bg:#50fa7b)\
$git_status\
[](fg:#50fa7b bg:#f1fa8c)\
$nodejs\
[](fg:#f1fa8c bg:#000000)\
$time\
[](fg:#000000)\
$character
"""

# Directory odule
[directory]
style = "bg:#ff5555 fg:#282a36"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ""

# Git branch module
[git_branch]
style = "bg:#8be9fd fg:#282a36"
format = "[ $symbol$branch ]($style)"
symbol = ""

# Git status module
[git_status]
style = "bg:#50fa7b fg:#282a36"
format = "[ $all_status ]($style)"

# Node.js module
[nodejs]
style = "bg:#f1fa8c fg:#282a36"
format = "[ $version ]($style)"

# Time module
[time]
disabled = false
time_format = "%R"
style = "bg:#000000 fg:#f8f8f2"
format = "[ $time ]($style)"

# Character module
[character]
success_symbol = "[➜](bold fg:#50fa7b)"
error_symbol = "[✗](bold fg:#ff5555)"

